# https://alacritty.org/config-alacritty.html
#
[font]
size = 14
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.cursor]
# cursor = '#ffffff'
cursor = '#eb8d00'
[colors.vi_mode_cursor]
	cursor = "#f5ef42"

[cursor.style]
shape = "Block"
blinking = "On"

[cursor.vi_mode_style]
shape = "Block"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[shell]
program = "zsh"

[window]
option_as_alt = "Both"
