# https://alacritty.org/config-alacritty.html
#
[font]
size = 14

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[colors.cursor]
cursor = '#FFFFFF'

[cursor.style]
shape = "Block"
blinking = "On"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[shell]
program = "zsh"

[window]
option_as_alt = "Both"
