#
# I am using this file when doing a clean install of Homebrew or when I want to
# update Homebrew, formulae and casks.
#
# To use this bundle, just run 'brew_bundle' and Brewfile will be used.
# You can also use directory-specific bundling with: brew bundle ~/mydir/mybrewfile
#
# To install Homebrew - ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"


### ---------------------------------------------------- ###
### Update                                               ###
### ---------------------------------------------------- ###
update || true
upgrade || true


### ---------------------------------------------------- ###
### Install formulae                                     ###
### ---------------------------------------------------- ###
tap homebrew/completions || true            `# completions `
tap caskroom/drivers || true                `# cask drivers`
tap jesseduffield/lazygit                   `# tap for lazygit`

install apple-gcc42 || true                 `# gcc for osx` 
install android-sdk || true                 `# android sdk`
install aria2 || true                       `# multi-protocol & multi-source command-line download utility`
install asciinema || true                   `# record and share terminal sessions`
install bash-completion || true
install brew-cask-completion || true
install ccat                                `# colorizing cat ` 
install cloc                                `# count lines of code ` 
install cowsay                              `# the cow says ` 
install ctop                                `# top-like interface for container metrics ` 
install curl || true                        `# curl`
install dfc || true                         `# displays file system space usage using graphs and colors`
install diff-pdf || true                    `# visually compare two PDF files`
install dir-env || true                     `# load/unload environment variables based on $PWD`
install doxygen                             `# Generate documentation from source code` 
install fasd || true                        `# quick access to files and directories`
install ffmpeg || true                      `# record, convert and stream audio and video`
install fzf || true                         `# a command-line fuzzy finder`
install ffmpeg || true                      `# to record, convert and stream audio and video` 
install go || true                          `# golang sdk`
install ghq || true                         `# git remote repository management made easy`
install gibo || true                        `# easily accessing gitignore boilerplates`
install git || true                         `# cli client for git`
install git-flow-avh || true                `# git-flow addon for git client`
install git-secret || true                  `# scan git commits for secrets and credentials`
install gnupg || true                       `# gpg`
install htop || true                        `# an interactive process viewer for Unix`
install httpie || true                      `# HTTP command-line client`
install hugo || true                        `# open-source static site generator`
install icdiff || true                      `# improved colored diff`
install imagemagick || true                 `# create, edit, compose, or convert bitmap images`
install jenv || true                        `# manage your java environment`
install jq || true                          `# command-line JSON processor, like sed`
install jo || true                          `# small utility to create JSON objects`
install joplin || true                      `# note taking and to-do application `
install kompose || true                     `# A conversion tool to go from Docker Compose to Kubernetes`
install kubectl || true                     `# kubernetes` 
install lazygit || true                        `# simple terminal UI for git commands` 
install lnav || true                        `# watch and analyze your log files from a terminal.` 
install mackup || true                      `# keep application settings in sync` 
install maven-completion || true
install mas || true                         `# Mac App Store command-line interface`
install midnight-commander || true          `# visual file manager`
install mplayer || true                     `# UNIX movie player`
install ncdu || true                        `# a disk usage analyzer with an ncurses interface`
install nmap || true                        `# port scanning utility for large networks`
install node || true                        `# node.js`
install openshift-cli || true               `# openshift cli` 
install plantuml || true                    `# draw UML diagrams`
install pip-completion || true
install potrace || true                     `# transforming bitmaps into vector graphics`
install python || true                      `# python programming`
install rest-shell || true                  `# Spring HATEOAS-compliant REST shell`
install ripgrep || true                     `# recursively searches directories for a regex pattern`
install ruby || true                        `# ruby environment`
install ssh-copy-id || true                 `# ssh copy `
install stunnel || true                     `# SSL tunneling program`
install the_silver_searcher || true         `# ag a code searching tool similar to ack`
install tig || true                         `# text-mode interface for git`
install tmux || true                        `# terminal multiplexer`
install tree || true                        `# list contents of directories in a tree-like format`
install vim || true                         `# highly configurable text editor`
install watch || true                       `# execute a program periodically and watch the output`
install wget || true                        `# non-interactive network downloader`
install yarn || true                        `# JavaScript package manager`
install youtube-dl || true                  `# download videos from youtube and many more sites`

### ---------------------------------------------------- ###
### Install casks (http://caskroom.io/)                  ###
### ---------------------------------------------------- ###
# Note: Casks with version 'latest' will not be updated due to no checksum change
cask install adium || true
cask install alfred || true                 `# amust have for boost productivity `
cask alfred link || true
cask install android-studio || true         `# android IDE `
cask install android-file-transfer || true  `# transfer files from Android device `
cask install atom || true                   `# yet another editor`
cask install brave || true
cask install bitbar || true
cask install calibre || true                `# e-book reader and library management application`
cask install clementine || true             `# music player and radio streamer`
cask install cyberduck || true              `# client for FTP and SFTP, WebDAV, and cloud storage`
cask install dash || true                   `# API documentation browser`
cask install dbvisualizer || true           `# universal database tool`
cask install docker || true                 `# docker for mac`
install docker-completion || true           `# docker completion`
install docker-compose-completion || true   `# docker compose completion`
install docker-machine-completion || true   `# docker machine completion`
cask install eclipse-java                   `# eclipse ide for java developers`
cask install etcher                         `# Burn images to SD cards & USB drives, safely and easily.`
cask install evernote || true               `# taking notes`
cask install filezilla || true              `# client for FTP and SFTP`
cask install flux || true                   `# get rid of the blue light`
cask install firefox-developer-edition || true  `# a browser`
cask install gimp || true                   `# an Image Editor (I probably never be able to learn)`
cask install gitkraken || true              `# Git GUI client for Windows, Mac and Linux `
cask install gitup || true                  `# awesome Git Gui Client `
cask install google-chrome || true          `# a browser` 
cask install google-photos-backup-and-sync || true `# Google Photos Backup And Sync`
cask install hammerspoon || true            `# powerful automation of MacOS`
cask install hyperswitch || true            `# awesome keyboard window switcher for Mac`
cask install icolors || true                `# a color picker and hex converter`
cask install inkscape || true               `# A powerful, free design tool`
cask install insomnia || true               `# superduper rest client`
cask install intellij-idea || true          `# awesome java IDE`
cask install iterm2 || true                 `# Terminal emulator for macOS`
cask install joplin || true                 `# a FOSS note taking and to-do application`
cask install karabiner || true              `# keyboard customizer for macOS`
cask install keepassxc || true              `# a great FOSS Password Manager`
cask install keybase || true                `# Crypto for everyone!`
cask install markright || true              `# a markdown editor`
cask install meld || true                   `# visual diff and merge tool`
cask install minikube || true               `# kubernetes mini`
cask install minishift || true              `# openshift mini`
cask install moeditor || true               `# all-purpose markdown editor`
cask install opera || true                  `# browser`
cask install mysqlworkbench  || true        `# gui tool for mysql `
cask install paintbrush || true             `# clean and simple paint program`
cask install pencil || true                 `# open-source GUI prototyping tool`
cask install phoenix-slides || true         `# image viewer`
# https://github.com/sindresorhus/quick-look-plugins
cask install qlcolorcode qlstephen qlmarkdown quicklook-json qlprettypatch quicklook-csv qlimagesize webpquicklook suspicious-package || true
cask install robo-3t || true                `# free lightweight GUI for MongoDB `
cask install skype || true                  `# video conf`
cask install sketch || true                 `# sketchapp - design tool`
cask install sketch-toolbox || true         `# some useful plugins for sketchapp`
cask install sonos || true                  `# Sonos controller`
cask install spectacle || true              `# move and resize windows`
cask install sourcetree || true             `# awesome git client `
cask install spotify || true                `# music for everyone`
cask install vagrant || true                `# vm management`
install vagrant-completion || true
cask install virtualbox || true             `# virtualizer for x86 hardware`
cask install virtualbox-extension-pack || true
cask install visual-paradigm-ce || true     `# software modelling tool`
cask install visual-studio-code || true     `# a great editor`
cask install vlc || true                    `# media player`
cask install xquartz || true                `# X windows on Mac`
cask install yed || true                    `# Graph Editor`
## -- fonts
tap homebrew/cask-fonts || true
cask install font-fira-code || true         `# monospaced font with programming ligatures`
cask install font-go-mono || true           `# golang fonts`   
cask install font-hasklig || true           `# a code font with monospaced ligatures`
cask install font-inconsolata || true       `# a great programmers font`
cask install font-monoid || true            `# a ppen source coding font with ligatures`
cask install font-monoisome || true         `# monoid with Font Awesome support`

### ---------------------------------------------------- ###
### Cleanup                                              ###
### ---------------------------------------------------- ###
cask cleanup || true
cleanup || true
