#!/bin/sh
#
# Script containing shell configuration that works for all shells
# Use this for interactive non-login shells
echo "Running .shrc"

# Fix systems missing $USER
[ -z "$USER" ] && export USER=$(whoami)

# OS variables
case "$(uname)" in
  Linux*)  export LINUX=1;;
  CYGWIN*) export CYGWIN=1;;
  OS400*)  export OS400=1;;
  Darwin*) export OSX=1;;
esac

# locale, set swedish but with english text, see https://wiki.archlinux.org/index.php/locale
[ $OSX ] && { 
  # a fix to make all LC_* swedish except LC_MESSAGES 
  unset LC_ALL
  export LANG=sv_SE.UTF-8
  export LC_CTYPE=sv_SE.UTF-8
  export LC_MESSAGES=en_US.UTF-8
}
