#!/bin/sh
#
# Script containing shell configuration that works for all shells
# Use this for interactive non-login shells
echo "Running .shrc"

# Fix systems missing $USER
[ -z "$USER" ] && export USER=$(whoami)

# OS variables
case "$(uname)" in
  Linux*)  export LINUX=1;;
  CYGWIN*) export CYGWIN=1;;
  OS400*)  export OS400=1;;
  Darwin*) export OSX=1;;
esac

