"syntax on
"
"set noerrorbells
"set tabstop=4 softtabstop=4
"set shiftwidth=4
"set expandtab
"set nu
"set nowrap
"set smartcase
"set noswapfile
"set nobackup
"set undodir=~/vim/undodir
"set undofile
"set incsearch
"
"set colorcolumn=80
"highlight ColorColumn ctermbg=0 guibg=lightgrey
"
"call plug#begin('~/.vim/plugged')
"Plug 'morhetz/gruvbox'
"Plug 'jremmen/vim-ripgrep'
"Plug 'tpope/vim-fugitive'
""Plug 'leafgarland/typescript-vim'
"Plug 'vim-utils/vim-man'
""Plug 'lyuts/vim-rtags'
"Plug 'git@github.com:kien/ctrlp.vim.git'
"Plug 'Valloric/YouCompleteMe'
"Plug 'mbbill/undotree'
"call plug#end()
"

 
