# config for stylua, ref: https://github.com/JohnnyMorganz/StyLua
line_endings = "Unix"
column_width = 120
indent_type = "Spaces"
indent_width = 2
quote_style = "AutoPreferDouble"
call_parentheses = "NoSingleTable"
