#!/usr/bin/env bash

# See ~/.bashrc for information how bash startup files are loaded
echo "Running .bash_profile"

# Load in .bashrc
[ -f ~/.bashrc ] && source ~/.bashrc

[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
