#!/usr/bin/env bash

# Macos Settings
# This is my MacOs setting to be run when installing a new version of MacOs
#
# Kudos to:  
#         https://mths.be/macos
#         https://www.defaults-write.com/
#         http://krypted.com/mac-os-x/defaults-symbolichotkeys/
#
# Howto change defaults:
# We can use defaults (https://www.manpagez.com/man/1/defaults/) 
# or plutil (https://www.manpagez.com/man/1/plutil/)
# or PlistBuddy (https://www.manpagez.com/man/8/PlistBuddy/)
#
# Before doing any changes, run
#  $ defaults read > defaults_$(date +%F_%H:%M:%S).txt
#  Change the setting, the run
#  $ defaults read > defaults_$(date +%F_%H:%M:%S).txt
#  Doing this creates two files called 'defaults_{timestamp}.txt', before and after changes.
#  Diff those two files
#  $ diff defaults_XX defaults_YY
#  with this knowledge you can then open up the latest file in an editor, 
#  search for the bit that changed and try and work out the command to change it.

# Abort if not Macos.
[[ "$(uname)" == Darwin* ]] || {
	echo "Can only be run in Macos"
	return 1
}

echo "Close any open System Preferences panes, to prevent them from overriding settings we’re about to change"
osascript -e 'tell application "System Preferences" to quit'

echo "Ask for the administrator password upfront"
sudo -v

echo "Keep-alive: update existing sudo time stamp until script has finished"
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

echo -n "Set language and text formats"
defaults write NSGlobalDomain AppleLanguages -array "en-GB" "sv-SE"
defaults write NSGlobalDomain AppleLocale -string "en_SE"
defaults write NSGlobalDomain AppleMeasurementUnits -string "Centimeters"
defaults write NSGlobalDomain AppleMetricUnits -bool true
echo "  ✔"
echo -n "Set list sort order to Swedish standard sort order"
defaults write NSGlobalDomain AppleCollationOrder "sv@collation=standard"
echo "  ✔"
echo -n "Show language menu in the top right corner"
sudo defaults write /Library/Preferences/com.apple.loginwindow showInputMenu -bool true
echo "  ✔"
echo -n "Set the timezone; see sudo systemsetup -listtimezones for other values"
sudo systemsetup -settimezone "Europe/Stockholm" >/dev/null
echo "  ✔"
echo -n "Set menu bar clock format"
# Menu bar clock format
# "h:mm" Default
# "HH"   Use a 24-hour clock
# "a"    Show AM/PM
# "ss"   Display the time with seconds
defaults write com.apple.menuextra.clock DateFormat -string "EEE d MMM HH:mm"
echo "  ✔"
echo -n "Turn off the Character Accent Selector and re-enable Key repetition"
defaults write -g ApplePressAndHoldEnabled -bool false
echo "  ✔"

echo -n "Set computer name (as done via System Preferences → Sharing)"
read -p "Do you want to set the computer name ? (y/N) " choice;
choice=${choice:-n};
[[ "$choice" =~ ^([Yy])$ ]] && {
	read -p "Enter the new computer name. Press Ctrl+c to cancel.  " computer_name;
	read -p "Do you want use computer name '${computer_name}'? (Y/n) " choice2;
	choice2=${choice2:-Y};
	[[ "$choice2" =~ ^([Yy])$ ]] && {
		sudo scutil --set ComputerName "${computer_name}"
		sudo scutil --set HostName "${computer_name}"
		sudo scutil --set LocalHostName "${computer_name}"
		sudo defaults write /Library/Preferences/SystemConfiguration/com.apple.smb.server NetBIOSName -string "${computer_name}"
		echo "  ✔"
	}
}

# # Set standby delay to 24 hours (default is 1 hour)
# sudo pmset -a standbydelay 86400

echo -n "Disable the sound effects on boot"
sudo nvram SystemAudioVolume=" "
echo "  ✔"

echo -n "Expand save panel by default"
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode -bool true
defaults write NSGlobalDomain NSNavPanelExpandedStateForSaveMode2 -bool true
echo "  ✔"

echo -n "Expand print panel by default"
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint -bool true
defaults write NSGlobalDomain PMPrintingExpandedStateForPrint2 -bool true
echo "  ✔"

echo -n "Save to disk (not to iCloud) by default"
defaults write NSGlobalDomain NSDocumentSaveNewDocumentsToCloud -bool false
echo "  ✔"

echo -n "Automatically quit printer app once the print jobs complete"
defaults write com.apple.print.PrintingPrefs "Quit When Finished" -bool true
echo "  ✔"

echo -n "Disable the “Are you sure you want to open this application?” dialog"
defaults write com.apple.LaunchServices LSQuarantine -bool false
echo "  ✔"

###############################################################################
# Keyboard                                                                    #
###############################################################################
# keyboard:text
echo -n "Turn off 'Correct spelling automatically'"
defaults write NSGlobalDomain NSAutomaticSpellingCorrectionEnabled -bool false
echo "  ✔"
echo -n "Turn off 'Capitalise words automatically'"
defaults write NSGlobalDomain NSAutomaticCapitalizationEnabled -bool false
echo "  ✔"
echo -n "Turn off 'Add full stop with double-space'"
defaults write NSGlobalDomain NSAutomaticPeriodSubstitutionEnabled -bool false
echo "  ✔"
echo -n "Turn off 'Touch Bar typing suggestions'"
defaults write NSGlobalDomain NSAutomaticTextCompletionEnabled -bool false
echo "  ✔"
echo -n "Turn off 'Use smart quotes and dashes'"
defaults write NSGlobalDomain NSAutomaticQuoteSubstitutionEnabled -bool false
defaults write NSGlobalDomain NSAutomaticDashSubstitutionEnabled -bool false
echo "  ✔"


###############################################################################
# Hotkeys                                                                     #
###############################################################################

echo -n "Disable 'Spotlight: Show Spotlight search'"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
  "Set AppleSymbolicHotKeys:64:enabled false"
echo "  ✔"

echo -n "Enable 'Mission Control: Switch to Desktop 2' with Ctrl+2"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
  "Set AppleSymbolicHotKeys:119:enabled true"
echo "  ✔"
echo -n "Enable 'Mission Control: Switch to Desktop 3' with Ctrl+3"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
  "Set AppleSymbolicHotKeys:120:enabled true"
echo "  ✔"
echo -n "Enable 'Mission Control: Switch to Desktop 4' with Ctrl+4"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
  "Set AppleSymbolicHotKeys:121:enabled true"
echo "  ✔"
echo -n "Enable 'Mission Control: Switch to Desktop 5' with Ctrl+5"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
  "Set AppleSymbolicHotKeys:122:enabled true"
echo "  ✔"

echo -n "Disable 'App Shortcuts: Show Help Menu' with ⇧⌘/ (interferce IntelliJ)"
/usr/libexec/PlistBuddy ~/Library/Preferences/com.apple.symbolichotkeys.plist -c \
  "Set AppleSymbolicHotKeys:98:enabled false"
echo "  ✔"

###############################################################################
# Screen                                                                      #
###############################################################################

echo -n "Enable darkmode but only for menubar and dock"
defaults write NSGlobalDomain AppleInterfaceStyle -string "Light"
defaults write -g NSRequiresAquaSystemAppearance -bool true
defaults write NSGlobalDomain AppleInterfaceStyle -string "Dark"
echo "  ✔"

###############################################################################
# Finder                                                                      #
###############################################################################

echo -n "Finder: allow quitting via ⌘ + Q; doing so will also hide desktop icons"
defaults write com.apple.finder QuitMenuItem -bool true
echo "  ✔"

echo -n "Finder: disable window animations and Get Info animations"
defaults write com.apple.finder DisableAllAnimations -bool true
echo "  ✔"

echo -n "Set Desktop as the default location for new Finder windows"
# For other paths, use `PfLo` and `file:///full/path/here/`
defaults write com.apple.finder NewWindowTarget -string "PfDe"
defaults write com.apple.finder NewWindowTargetPath -string "file://${HOME}/Desktop/"
echo "  ✔"

echo -n "Show icons for hard drives, servers, and removable media on the desktop"
defaults write com.apple.finder ShowExternalHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowHardDrivesOnDesktop -bool true
defaults write com.apple.finder ShowMountedServersOnDesktop -bool true
defaults write com.apple.finder ShowRemovableMediaOnDesktop -bool true
echo "  ✔"

echo -n "Finder: show hidden files by default"
defaults write com.apple.finder AppleShowAllFiles -bool true
echo "  ✔"

echo -n "Finder: show all filename extensions"
defaults write NSGlobalDomain AppleShowAllExtensions -bool true
echo "  ✔"

echo -n "Finder: show status bar"
defaults write com.apple.finder ShowStatusBar -bool true
echo "  ✔"

echo -n "Finder: show path bar"
defaults write com.apple.finder ShowPathbar -bool true
echo "  ✔"

echo -n "Display full POSIX path as Finder window title"
defaults write com.apple.finder _FXShowPosixPathInTitle -bool true
echo "  ✔"

echo -n "Keep folders on top when sorting by name"
defaults write com.apple.finder _FXSortFoldersFirst -bool true
echo "  ✔"

echo -n "When performing a search, search the current folder by default"
# This Mac       : `SCev`
# Current Folder : `SCcf`
# Previous Scope : `SCsp`
defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"
echo "  ✔"

echo -n "Disable the warning when changing a file extension"
defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false
echo "  ✔"

echo -n "Enable spring loading for directories"
defaults write NSGlobalDomain com.apple.springing.enabled -bool true
echo "  ✔"

echo -n "Remove the spring loading delay for directories"
defaults write NSGlobalDomain com.apple.springing.delay -float 0
echo "  ✔"

echo -n "Avoid creating .DS_Store files on network or USB volumes"
defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true
defaults write com.apple.desktopservices DSDontWriteUSBStores -bool true
echo "  ✔"

echo -n "Use list view in all Finder windows by default"
# Four-letter codes for the other view modes: `icnv`, `clmv`, `Flwv`
defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"
echo "  ✔"

echo -n "Show the ~/Library folder"
chflags nohidden ~/Library
echo "  ✔"

echo -n "Show the /Volumes folder"
sudo chflags nohidden /Volumes
echo "  ✔"

echo -n "Expand File Info panes for 'General', 'Open with', and 'Sharing & Permissions'"
defaults write com.apple.finder FXInfoPanesExpanded -dict \
	General -bool true \
	OpenWith -bool true \
	Privileges -bool true
echo "  ✔"

###############################################################################
# Dock, Dashboard, Touchbar and hot corners                                   #
###############################################################################

echo -n "Turn off magnification (Dock)"
defaults write com.apple.dock magnification -bool false
echo "  ✔"

echo -n "Disable Dashboard"
defaults write com.apple.dashboard mcx-disabled -bool true
echo "  ✔"

echo -n "Don’t automatically rearrange Spaces based on most recent use"
defaults write com.apple.dock mru-spaces -bool false
echo "  ✔"

echo -n "Remove the auto-hiding Dock delay"
defaults write com.apple.dock autohide-delay -float 0
echo "  ✔"
echo -n "Remove the animation when hiding/showing the Dock"
defaults write com.apple.dock autohide-time-modifier -float 0
echo "  ✔"

echo -n "Automatically hide and show the Dock"
defaults write com.apple.dock autohide -bool true
echo "  ✔"

echo -n "Make Dock icons of hidden applications translucent"
defaults write com.apple.dock showhidden -bool true
echo "  ✔"

echo -n "Don’t show recent applications in Dock"
defaults write com.apple.dock show-recents -bool false
echo "  ✔"

echo -n "Always show date in Dock"
defaults write com.apple.menuextra.clock.plist ShowDate -int 1
echo "  ✔"

# Hot corners
# Possible values:
#  0: no-op
#  2: Mission Control
#  3: Show application windows
#  4: Desktop
#  5: Start screen saver
#  6: Disable screen saver
#  7: Dashboard
# 10: Put display to sleep
# 11: Launchpad
# 12: Notification Center
# 13: Lock Screen

# # Top left screen corner → Mission Control
# defaults write com.apple.dock wvous-tl-corner -int 2
# defaults write com.apple.dock wvous-tl-modifier -int 0
# # Top right screen corner → Desktop
# defaults write com.apple.dock wvous-tr-corner -int 4
# defaults write com.apple.dock wvous-tr-modifier -int 0
echo -n "Bottom left screen corner → Start screen saver"
defaults write com.apple.dock wvous-bl-corner -int 5
defaults write com.apple.dock wvous-bl-modifier -int 0
echo "  ✔"
echo -n "Bottom right screen corner → SLock screen"
defaults write com.apple.dock wvous-br-corner -int 13
defaults write com.apple.dock wvous-br-modifier -int 0
echo "  ✔"

echo -n "Always show function keys in touchbar"
defaults write com.apple.touchbar.agent PresentationModeGlobal -string "functionKeys"
echo "  ✔"

###############################################################################
# Terminal & iTerm 2                                                          #
###############################################################################

echo -n "Terminal: Only use UTF-8"
defaults write com.apple.terminal StringEncodings -array 4
echo "  ✔"

echo -n "iTerm2: Set font to 12pt Meslo LG M DZ Regular for Powerline"
# print value https://stackoverflow.com/a/20206222
/usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'Normal Font' MesloLGMDZForPowerline-Regular 12" ~/Library/Preferences/com.googlecode.iTerm2.plist
echo "  ✔"
echo -n "iTerm2: Set font to 12pt Meslo LG M DZ Regular for Powerline for non ascii characters"
/usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'Use Non-ASCII Font' true" ~/Library/Preferences/com.googlecode.iTerm2.plist
/usr/libexec/PlistBuddy -c "Set 'New Bookmarks':0:'Non Ascii Font' MesloLGMDZForPowerline-Regular 12" ~/Library/Preferences/com.googlecode.iTerm2.plist
echo "  ✔"

###############################################################################
# SourceTree                                                                 #
###############################################################################

echo -n "SourceTree: Don't restore windows on startup"
defaults write com.torusknot.SourceTreeNotMAS  windowRestorationMethod -int 1
echo "  ✔"

###############################################################################
# Time Machine                                                                #
###############################################################################

echo -n "Prevent Time Machine from prompting to use new hard drives as backup volume"
defaults write com.apple.TimeMachine DoNotOfferNewDisksForBackup -bool true
echo "  ✔"

###############################################################################
# Activity Monitor                                                            #
###############################################################################

echo -n "Show the main window when launching Activity Monitor"
defaults write com.apple.ActivityMonitor OpenMainWindow -bool true
echo "  ✔"

echo -n "Visualize CPU usage in the Activity Monitor Dock icon"
defaults write com.apple.ActivityMonitor IconType -int 5
echo "  ✔"

echo -n "Show all processes in Activity Monitor"
defaults write com.apple.ActivityMonitor ShowCategory -int 0
echo "  ✔"

echo -n "Sort Activity Monitor results by CPU usage"
defaults write com.apple.ActivityMonitor SortColumn -string "CPUUsage"
defaults write com.apple.ActivityMonitor SortDirection -int 0
echo "  ✔"

###############################################################################
# Mac App Store                                                               #
###############################################################################

echo -n "Enable the automatic update check"
defaults write com.apple.SoftwareUpdate AutomaticCheckEnabled -bool true
echo "  ✔"

echo -n "Check for software updates daily, not just once per week"
defaults write com.apple.SoftwareUpdate ScheduleFrequency -int 1
echo "  ✔"

echo -n "Download newly available updates in background"
defaults write com.apple.SoftwareUpdate AutomaticDownload -int 1
echo "  ✔"

echo -n "Install System data files & security updates"
defaults write com.apple.SoftwareUpdate CriticalUpdateInstall -int 1
echo "  ✔"

###############################################################################
# Photos                                                                      #
###############################################################################

echo -n "Prevent Photos from opening automatically when devices are plugged in"
defaults -currentHost write com.apple.ImageCapture disableHotPlug -bool true
echo "  ✔"

###############################################################################
# other application settings                                                  #
###############################################################################

## Microsoft Office
echo -n "Microsoft AutoUpdate should only check for updates (don't install)"
defaults write com.microsoft.autoupdate2 HowToCheck -string "AutomaticCheck"
echo "  ✔"

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Activity Monitor" \
	"Address Book" \
	"Calendar" \
	"cfprefsd" \
	"Contacts" \
	"Dock" \
	"Finder" \
	"Mail" \
	"Messages" \
	"Photos" \
	"Safari" \
	"SystemUIServer" \
	"ControlStrip"\
	"Touch Bar agent" \
	"Terminal" \
	"iCal"; do
	echo "Killing app ${app}"
	killall "${app}" &> /dev/null
done
echo "Done. Note that some of these changes require a logout/restart to take effect."
