# https://taskfile.dev
#
# This is my personal taskfile with tasks to be used everywhere in 
# different projects
#
# See alias tt

version: '3'

tasks:
  default: 
    desc: list all tasks with description
    cmds:
      - task -l
    silent: true

  
  # ------------------------------------------------------------------------------- #
  # Maven commands
  # ------------------------------------------------------------------------------- #
  mvn:dependency:relocated:
    desc: check for relocated dependencies with 'oga-maven-plugin'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: "mvn biz.lermitage.oga:oga-maven-plugin:check --fail-never"

  mvn:dependency:tree:
    desc: print dependency tree 
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: "mvn dependency:tree -X"

  mvn:effective-pom:
    desc: print effective pom
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: "mvn help:effective-pom"

  mvn:build-plan:
    desc: print lifecycles, phaces and goals  
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: "mvn fr.jcgay.maven.plugins:buildplan-maven-plugin:list"

