# https://taskfile.dev
#
# This is my personal taskfile with tasks to be used everywhere in 
# different projects
#
# See alias tt

version: '3'

tasks:
  default: 
    desc: list all tasks with description
    cmds:
      - task -l
    silent: true

  
  # ------------------------------------------------------------------------------- #
  # Maven commands
  # ------------------------------------------------------------------------------- #
  mvn:dependency:relocated:
    desc: check for relocated dependencies with 'oga-maven-plugin'
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: mvn -U biz.lermitage.oga:oga-maven-plugin:check --fail-never {{.CLI_ARGS}}

  mvn:dependency:tree:
    desc: print dependency tree 
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: mvn -U dependency:tree -X {{.CLI_ARGS}}

  mvn:effective-pom:
    desc: print effective pom
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: mvn -U help:effective-pom {{.CLI_ARGS}}

  mvn:build-plan:
    desc: print lifecycles, phaces and goals  
    dir: '{{.USER_WORKING_DIR}}'
    cmds:
      - cmd: mvn -U fr.jcgay.maven.plugins:buildplan-maven-plugin:list {{.CLI_ARGS}}

  mvn:openrewrite:deprecated:
    desc: find uses of deprecated classes, methods, and fields
    dir: '{{.USER_WORKING_DIR}}'
    prompt: This action will update source code with markers. Make sure your repository is clean before running this task.
    cmds:
      - cmd: mvn -U org.openrewrite.maven:rewrite-maven-plugin:run -Drewrite.activeRecipes=org.openrewrite.java.search.FindDeprecatedUses {{.CLI_ARGS}}

