#!/bin/sh
#
# My list of aliases and they are shell agnostic

has() {  # has command?
   command -v $1 >/dev/null 2>&1 && return 0 || return 1
}

# Navigation -----------------------
# typo; get rid of 'command not found'
alias cd..='cd ..'

# a quick way to get out of current directory
alias ..='cd ..'
alias ...='cd ../../'
alias ....='cd ../../../'
alias .....='cd ../../../../'
alias ......='cd ../../../../../'
alias .......='cd ../../../../../../'
alias ........='cd ../../../../../../../'
alias .........='cd ../../../../../../../../'

# ----------------
# sudo and alias. If the last character of the alias value is a blank,
# then the next command word following the alias is also checked for alias expansion.
alias sudo='sudo '

# Make some possibly destructive commands more interactive.
alias rm='rm -i'
alias mv='mv -i'
alias cp='cp -i'
#Nice try but it didn't work in OS X
#alias chown='chown --preserve-root'
#alias chmod='chmod --preserve-root'
#alias chgrp='chgrp --preserve-root'

# Alias's to modified commands
# $ \vi        # ignore alias named "vi"
# $ "vi"       # ignore alias named "vi"
# $ command vi # ignore functions and aliases
alias vi='vim'
alias grep='grep --color=auto'   # Highlight matches
alias egrep='egrep --color=auto' # Highlight matches
alias fgrep='fgrep --color=auto' # Highlight matches
alias bc='bc -l'
alias wget='wget -c'
alias ln='ln -i'
alias ncdu='ncdu --color dark' # NCurses Disk Usage
command -v ccat >/dev/null 2>&1 && alias cat='ccat' # colorizing cat
command -v dfc >/dev/null 2>&1 && alias df='dfc' # colorized df

#tmux
alias tm='tmux'
#tmux start; attach to an existing session or restore resurrect https://github.com/tmux-plugins/tmux-resurrect/issues/139#issuecomment-241715139
alias tms='tmux attach || { (while ! tmux run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh; do sleep 0.2; done)& tmux ; }'
alias tma='tmux a -t '   # tmux attach a target session

# copy/paste command with prompt string into the shell
# alias $='__prompt_string_'
# alias #='__prompt_string_'

# Alias to multiple ls commands
# Detect which `ls` flavor is in use
if ls --color > /dev/null 2>&1; then
	colorflag="--color" # GNU `ls`
else
	colorflag="-G"      # OS X `ls`
fi
# shellcheck disable=SC2139
alias ls="ls -aF ${colorflag}"    # show hidden and type suffix
alias ll='ls -la'               # show hidden and sort by modified
# shellcheck disable=SC2139
alias l.="ls -dl ${colorflag} .*" # show only hidden files
alias lx='ls -lXB'                # sort by extension
alias lk='ls -lSr'                # sort by size
alias lc='ls -lcr'		            # sort by change time
alias lu='ls -lur'		            # sort by access time
alias lr='ls -lR'                 # recursive ls
alias lt='ls -ltr'                # sort by date
alias lm='ls -al |more'           # pipe through 'more'
alias la='ls -ltraFh'             # show all
alias lla='ls -lah'               # list all and human readable
alias g='grep -i'  # Case insensitive grep
alias f='find . -iname'
alias m='more'
alias t='task'
# shellcheck disable=SC2139
alias tt="task --taskfile $XDG_CONFIG_HOME/go-task/Taskfile.yaml"
alias df='df -h'
alias hist='history | grep $1' #requires an argument
alias pg='ps aux | grep'  #requires an argument
alias un='tar -zxvf'
alias mountedinfo='df -hT'
alias openports='netstat -nape --inet'
alias reload='clear; exec $SHELL'
alias rr="reload"
alias ns='netstat -alnp --protocol=inet | grep -v CLOSE_WAIT | cut -c-6,21-94 | tail +2'
alias listen="lsof -P -i -n"
alias du1='du -h --max-depth=1'
alias ducks='du -cksh * | sort -rn|head -11' # Lists folders and files sizes in the current folder
alias da='date "+%Y-%m-%d %A    %T %Z"'
alias scp-bash='scp ~/.bashrc ~/.bash_completion ~/.bash_profile ~/.profile ~/.bash_functions ~/.bash_aliases ~/.functions ~/.aliases' # copy bash files to server, requires username@hostname:
alias veewee='bundle exec veewee'  # do the veewee
alias g='git'
alias gg='lazygit'
command -v nvim >/dev/null 2>&1 && alias vim="nvim"
alias v="vim"
alias j=z         # fasd z with better key location
alias jj=zz       # fasd zz with better key location
alias rtfm='tldr'
alias lazygit='LG_CONFIG_FILE="$HOME/.config/lazygit/config.yaml" lazygit'
alias lzg='lazygit'
alias lzd='lazydocker'
command -v gdu-go >/dev/null 2>&1 && alias gdu="gdu-go"
# ghq
alias ghg='__ghg(){ ghq get -l "${1}" && cd .; }; __ghg'
#kubernetes aliase(s)
alias k='kubectl'
alias kim="kubectl get pods -o jsonpath=\"{.items[*].spec.containers[*].image}\" |\
          tr -s '[[:space:]]' '\\n' | sort | uniq -c" #list images in current ns
alias kpf='kubectl port-forward '
# kustomize
alias kz='kustomize'
# skaffold
alias sk=skaffold
alias mk='minikube'
alias zj="zellij"
alias zja="zellij a"
alias zjs="zellij -s"
alias zjr="zellij run -f --"

# maven
alias mct='mvn clean test'
alias mcv='mvn clean verify'
alias mcp='mvn clean package'
alias mcpt!='mvn clean package -DskipTests'
alias msbr='mvn spring-boot:run'
alias msbtr='mvn spring-boot:test-run'
alias mcsbr='mvn clean spring-boot:run'
alias mcsbtr='mvn clean spring-boot:test-run'
alias msbrd='mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"'
alias mpv='mvn_print_version'
alias mdb='mvn docker:build'
alias mtc7='mvn tomcat7:run'
alias mvnct='mvn clean test'
alias mvncv='mvn clean verify'
alias mvncp='mvn clean package'
alias mvnci='mvn clean install'
alias mvnsbr='mvn spring-boot:run'
alias mvncsbr='mvn clean spring-boot:run'
alias mvnsbrd='mvn spring-boot:run -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"'
alias mvnpv='mvn_print_version'
alias mvndb='mvn docker:build'
alias mvntc7='mvn tomcat7:run'

alias mk='minikube'
# golang aliases
alias gof='gofmt'
alias gofl='gofmt -s -l'
alias gofw='gofmt -s -w'
alias got='go test'
alias gotv='go test -v'
alias gob='go build'

#docker aliases and functions
alias d='docker'
! [ -n "$ZSH_VERSION" ] && complete -F _docker d
alias dc='docker-compose'
! [ -n "$ZSH_VERSION" ] && complete -F _docker_compose dc
alias dm='docker-machine'
! [ -n "$ZSH_VERSION" ] && complete -F _docker_machine dm

# nnn, because it's in my muscle memory
alias nnn='yazi' # yazi file manager

[ $OSX ] && { # OS X specific aliases
  # Java (using jenv instead)
  #alias setJdk6='export JAVA_HOME=$(/usr/libexec/java_home -v 1.6)'
  #alias setJdk7='export JAVA_HOME=$(/usr/libexec/java_home -v 1.7)'
  #alias setJdk8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
  #[ $OSX ] && alias brew-update='sudo chown -R $(whoami):admin /usr/local && brew update && brew outdated'
  # Homebrew
  alias brew-update='brew update && brew outdated'
  alias brew-upgrade='brew upgrade && brew cleanup'
  # make python 3 default
  alias python='/usr/local/bin/python3'
  alias pip='/usr/local/bin/pip3'
  # When it's time for a fika
  alias fika="/System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend"
  # Pretty print from clipboard, OS X only
  alias xmlformatclipboard='pbpaste | xmllint --format -'
  # Merge PDF files, usage: 'mergepdf -o output.pdf input{1,2,3}.pdf'
  alias mergepdf='/System/Library/Automator/Combine\ PDF\ Pages.action/Contents/Resources/join.py'
  # OS X has no `md5sum`, so use `md5` as a fallback
  has md5sum || alias md5sum="md5"
  # OS X has no `sha1sum`, so use `shasum` as a fallback
  has sha1sum || alias sha1sum="shasum"
  # Show/hide hidden files in Finder
  alias show="defaults write com.apple.finder AppleShowAllFiles -bool true && killall Finder"
  alias hide="defaults write com.apple.finder AppleShowAllFiles -bool false && killall Finder"
  # Hide/show all desktop icons (useful when presenting)
  alias hidedesktop="defaults write com.apple.finder CreateDesktop -bool false && killall Finder"
  alias showdesktop="defaults write com.apple.finder CreateDesktop -bool true && killall Finder"
  alias ij='idea'
  alias openports='sudo lsof -PiTCP -sTCP:LISTEN'
}


# HTTPie aliases (https://github.com/jkbrzt/httpie)
alias GET="http"
alias POST="http POST"
alias HEAD="http HEAD"

# Enumerate every column ()
alias fields="awk 'NR == 1 { for (i=1;i<=NF;i++) {printf i \" \"} print \"\"} {print}' | column -t"

# Shows most used commands, cool script I got this from: http://lifehacker.com/software/how-to/turbocharge-your-terminal-274317.php
alias profileme="history | awk '{print \$2}' | awk 'BEGIN{FS=\"|\"}{print \$1}' | sort | uniq -c | sort -n | tail -n 20 | sort -nr"

# just for fun
alias matrix='LC_ALL=C tr -c "[:digit:]" " " < /dev/urandom | dd cbs=$COLUMNS conv=unblock | GREP_COLOR="1;32" grep --color "[^ ]"'

#play youtube videos
alias play-yt='__play-youtube_() { yt-dlp -q -o- "${1:=https://www.youtube.com/watch?v=dQw4w9WgXcQ}" | mplayer -cache 8192 -; }; __play-youtube_'
# check the weather
alias weather='__weather(){ curl -4 wttr.in/"${1:=gothenburg}"; }; __weather'

# shortcuts to be expanded
[ -n "$ZSH_VERSION" ] && { global='-g'; }
alias "${global}" L='| less '                 # less
alias "${global}" M='| more '                 # more
alias "${global}" C='| wc -l '                # count number of lines
alias "${global}" H='| head '                 # head
alias "${global}" T='| tail '                 # tail
alias "${global}" G='| grep -i'               # grep
alias "${global}" X='| xargs '                # xargs
alias "${global}" Z='| fzf '                  # fzf
alias "${global}" ZP="| fzf --ansi --preview 'bat {-1} --color=always'"  # fzf with preview
alias "${global}" V='| vim '                  # vim
alias "${global}" TEE='| tee >( grep -i 'filter' > filter.log ) output.log'  # tee with filter
alias "${global}" LL='2>&1 | less '           # pipe stderr and stdout to less
alias "${global}" NE='2> /dev/null'           # stderr to devnull
alias "${global}" NUL='> /dev/null 2>&1'      # send all output to dev/null
alias "${global}" JQ="| jq -Rrc '. as \$line | fromjson? // \$line'"          #output: json and non-json
alias "${global}" JQO="| jq -R 'fromjson? | .'"                               #output: only json
alias "${global}" JQP="| jq -R -r '. as \$line | try fromjson catch \$line'"  #output: json pretty print and non-json
alias "${global}" JQPP="| tr \"\\n\" \"\n\" | jq -R -r '. as \$line | try fromjson catch \$line'"  #output: json pretty print and non-json
alias "${global}" PF="8080:8080 8081:8081"                            #port-forward
alias "${global}" FORF="for f in ./*; do echo \$f; done"              #loop over files
alias "${global}" FORD="for d in */; do echo \$d; done"               #loop over dirs
alias "${global}" MT!=' -DskipTests'          # skip tests in Maven
alias "${global}" MD=' -Dspring-boot.run.jvmArguments="-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=y,address=5005"'  # spring-boot debug properties

