#!/usr/bin/env zsh
# Executes commands at logout.
#
# This file is sourced by login shells during logout. It should be used for
# displaying messages and the deletion of files.

# echo "Running .zlogout"

# Print the message.
cat <<-EOF

Ok, logging out.

EOF

