#!/usr/bin/env zsh
#
# Defines environment variables.
# This file is sourced by all instances of Zsh (interactive, non-interactive, login and non-login ), 
# and thus, it should be kept as small as possible and should only define environment variables.

#echo "Running .zshenv"

# Ensure that a non-login, non-interactive shell has a defined environment.
if [[ "$SHLVL" -eq 1 && ! -o LOGIN && -s "${ZDOTDIR:-$HOME}/.zprofile" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprofile"
fi

#
# Editors
#
export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

# file names to ignore 
zstyle ':completion:*:*files' ignored-patterns '.DS_Store'
# Typing EOF (CTRL+D) will not exit interactive sessions
setopt ignoreeof

# define Zim location
export ZIM_HOME=${HOME}/.local/zim

