-- override/extend lazyvim default config

-- https://mason-registry.dev/registry/list
local preferred_packages = {
  "bash-language-server",
  "beautysh",
  "black",
  "cmake-language-server",
  "cucumber-language-server",
  "codelldb",
  "css-lsp",
  "dart-debug-adapter",
  "deno",
  "diagnostic-languageserver",
  "dockerfile-language-server",
  "emmet-ls",
  "eslint-lsp",
  "eslint_d",
  "flake8",
  "go-debug-adapter",
  "goimports",
  "golangci-lint",
  "gopls",
  "gotests",
  "gotestsum",
  "gradle-language-server",
  "graphql-language-service-cli",
  "groovy-language-server",
  "hadolint",
  "html-lsp",
  "isort",
  "java-debug-adapter",
  "java-test",
  "jdtls",
  "jq",
  "json-lsp",
  "kotlin-debug-adapter",
  "kotlin-language-server",
  "ktlint",
  "lemminx",
  "lua-language-server",
  "lua-language-server",
  "luacheck",
  "luaformatter",
  "marksman",
  "prettierd",
  "python-lsp-server",
  "rust-analyzer",
  "rustfmt",
  "selene",
  "shellcheck",
  "shfmt",
  "sql-formatter",
  "sqlls",
  "stylua",
  "svelte-language-server",
  "tailwindcss-language-server",
  "taplo",
  "terraform-ls",
  "typescript-language-server",
  "vue-language-server",
  "yaml-language-server",
  "yamlfmt",
  "yamllint",
  -- "flake8",
}

return {
  "williamboman/mason.nvim",
  opts = {
    ensure_installed = preferred_packages,
  }
}
