#!/usr/bin/env bash

# --------
# Manage Python packages
# ------

# resolve links - $0 may be a softlink
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done
PRGDIR=`dirname "$PRG"`
source "$PRGDIR"/../scripts/include.sh

install() {
    if ! command -v pip3 >/dev/null 2>&1; then
        error "pip3 is not installed"
        exit 1
    fi
    info "Installing python packages.. (pip3 -r)"
    pip3 -r $home/.config/python/requirement.txt 
    success
}

upgrade() {
    info "Upgrading python packages...(brew upgrade)"
    for i in $(pip3 list -o | awk 'NR > 2 {print $1}'); do pip3 install -U $i; done
    success
}

main() {
    heading "Managing python"
    read -p "Do you want to install/update Python packages? (Y/n) " choice;
    choice=${choice:-Y};
    [[ "$choice" =~ ^([Yy])$ ]] || exit 0;
    install
    upgrade
    success "Done pything"
}

main