#!/usr/bin/env bash

# --------
# Manage Python packages
# ------
set -eo pipefail

# resolve links - $0 may be a softlink
PRG="$0"
while [ -h "$PRG" ] ; do
  ls=`ls -ld "$PRG"`
  link=`expr "$ls" : '.*-> \(.*\)$'`
  if expr "$link" : '/.*' > /dev/null; then
    PRG="$link"
  else
    PRG=`dirname "$PRG"`/"$link"
  fi
done
PRGDIR=`dirname "$PRG"`
source "$PRGDIR"/../scripts/include.sh
pip="pip3"

install() {
    if command -v "${pip}" >/dev/null 2>&1; then
      info "Installing python packages.. (pip -r)"
      eval "${pip} install -r $HOME/.config/python/requirement.txt"
      success
    else
      error "${pip} is not installed"
      exit 1
    fi
}

upgrade() {
    info "Upgrading python packages...(pip install -U)"
    for i in $(${pip} list -o | awk 'NR > 2 {print $1}'); do 
      eval "${pip} install -U $i"; 
    done
    success
}

main() {
    heading "Managing python"
    read -p "Do you want to install/update Python packages? (Y/n) " choice;
    choice=${choice:-Y};
    [[ "$choice" =~ ^([Yy])$ ]] || exit 0;
    install
    upgrade
    success "Done pything"
}

main