#!/usr/bin/env zsh
# This file is sourced by interactive shells. It should define aliases,
# functions, shell options, and key bindings.

# http://zsh.sourceforge.net/Intro/intro_toc.html#SEC16

# .zshenv is always sourced, it often contains exported variables that 
# should be available to other programs. For example, $PATH, $EDITOR, and $PAGER 
# are often set in .zshenv. Also, you can set $ZDOTDIR in .zshenv to specify an 
# alternative location for the rest of your zsh configuration.
# 
# .zshrc is for interactive shell configuration. You set options for the interactive 
# shell there with the setopt and unsetopt commands. You can also load shell modules, 
# set your history options, change your prompt, set up zle and completion, et cetera. 
# You also set any variables that are only used in the interactive shell (e.g. $LS_COLORS).
# 
# .zlogin is sourced on the start of a login shell. This file is often used to start X 
# using startx. Some systems start X on boot, so this file is not always very useful.
# 
# .zprofile is basically the same as .zlogin except that it's sourced directly before 
# .zshrc is sourced instead of directly after it. According to the zsh documentation, 
# ".zprofile is meant as an alternative to `.zlogin' for ksh fans; the two are not 
# intended to be used together, although this could certainly be done if desired."
# 
# .zlogout is sometimes used to clear and reset the terminal.

echo "Running .zshrc"

# load shared shell configuration
[ -f ~/.shrc ] && source ~/.shrc

# Use zsh framework  -------------------------------------------------------
# Source zim
if [[ -s ${ZDOTDIR:-${HOME}}/.zim/init.zsh ]]; then
  source ${ZDOTDIR:-${HOME}}/.zim/init.zsh
fi
# Source Prezto.
#if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
#  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
#fi

# Personal settings below  -------------------------------------------------------

# ---------------------------------------------------------------------------------------------
# Liquid prompt -- A useful adaptive prompt for Bash & Zsh
# Only load Liquid Prompt in interactive shells, not from a script or from scp
# Only load if  zprompt_theme (zim) is not set and liquidprompt exists
if [[ $- = *i* ]] && [[ -z ${zprompt_theme} ]] && [[ -s ${ZDOTDIR:-${HOME}}/.liquidprompt/liquidprompt ]]; then
  source ~/.liquidprompt/liquidprompt
fi

# turn on autocomplete
autoload -Uz compinit
compinit
# autocompletion with an arrow-key driven interface
zstyle ':completion:*' menu select
#Change directories with variable names
setopt cdablevars

#globdots lets files beginning with a . be matched without explicitly specifying the dot.
setopt globdots

# extendedglob gives ability to do l -l **/*(^U)
setopt extendedglob

#correct turns on spelling correction for commands
setopt correct

#Report the status of background jobs immediately, rather than waiting until just before printing a prompt
setopt notify

#no beep, 
unsetopt beep 

#If a pattern for filename generation has no matches, print an error,
#instead of leaving it unchanged in the argument list. This also 
#applies to file expansion of an initial ~ or =.
unsetopt nomatch

#use emacs binding
#bindkey -e

#Use up key to search backward in the history for a line beginning with the current line up to the cursor.
bindkey '\e[A' history-beginning-search-backward
#Use down key to search forward in the history for a line beginning with the current line up to the cursor.
bindkey '\e[B' history-beginning-search-forward

# Using Base16 for Shells https://github.com/chriskempson/base16-shell
BASE16_SHELL=$HOME/.config/base16-shell/
[ -n "$PS1" ] && [ -s $BASE16_SHELL/profile_helper.sh ] && eval "$($BASE16_SHELL/profile_helper.sh)"

# fzf for fuzzy file mathing
[ -f ~/.fzf.zsh ] && {
  source ~/.fzf.zsh
  # Setting ag as the default source for fzf
  command -v ag >/dev/null 2>&1 && export FZF_DEFAULT_COMMAND='ag -g ""'
}

# Functions  -------------------------------------------------------
[ -f ~/.functions ] && source ~/.functions
[ -f ~/.zsh_functions ] && source ~/.zsh_functions

# Aliases            -------------------------------------------------------
[ -f ~/.aliases ] && source ~/.aliases
[ -f ~/zsh_aliases ] && source ~/.zsh_aliases


##############################################################################
# Local Config
##############################################################################

# use .zshrc.local for settings specific to local system
[[ -f ~/.zshrc.local ]] && source ~/.zshrc.local

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
