"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[manager]

prepend_keymap = [


  { on = [ "J" ], run = "plugin --sync parent-arrow --args=1" },
  { on = [ "K" ], run = "plugin --sync parent-arrow --args=-1" },

  { on  = [ "\\", "z" ], run = "plugin --sync max-preview", desc = "Zoom" },

  { on = [ "e", ], run = "open", desc = "Open the selected files" },
  { on = [ "E", ], run = "open --interactive", desc = "Open the selected files interactively" },
  { on = [ "g", ".", ], run = "cd ~/.dotfiles", desc = "Go to .dotfiles directory" },
  { on = [ "g", "/" ], run = '''shell "$SHELL" --block --confirm''', desc = "Open shell here" },
  { on = [ "g", "?" ], run = "help", desc = "Open help" },
  { on = [ "g", "c", ], run = "cd ~/.config", desc = "Go to the .config directory" },
  { on = [ "g", "d", ], run = "cd ~/Downloads", desc = "Go to the Downloads directory" },
  { on = [ "g", "D", ], run = "cd ~/Documents", desc = "Go to the Documents directory" },
  { on = [ "g", "l", ], run = "cd ~/.local", desc = "Go to the .local directory" },
  { on = [ "g", "V", ], run = "cd /Volumes", desc = "Go to the /Volume directory" },
  { on = [ "g", "n", ], run = "cd ~/.config/nvim", desc = "Go to the nvim directory" },
  { on = [ "g", "N", ], run = "cd ~/Notes", desc = "Go to the Notes directory" },
  { on = [ "g", "p", ], run = "cd ~/Pictures", desc = "Go to the Pictures directory" },
  { on = [ "g", "r", ], run = "cd ~/Repos", desc = "Go to the ~/Repos directory" },
  { on = [ "g", "x", "c" ], run = "cd $XDG_CONFIG_HOME", desc = "Go to the $XDG_CONFIG_HOME directory" },
  { on = [ "g", "x", "C" ], run = "cd $XDG_CACHE_HOME", desc = "Go to the $XDG_CACHE_HOME directory" },
  { on = [ "g", "x", "d" ], run = "cd $XDG_DATA_HOME", desc = "Go to the $XDG_DATA_HOME directory" },
  { on = [ "g", "x", "s" ], run = "cd $XDG_STATE_HOME", desc = "Go to the $XDG_STATE_HOME directory" },
  { on = [ "<C-s>" ], run  = 'shell "$SHELL" --block --confirm', desc = "Open shell here" },
]

[input]

prepend_keymap = [{ on = ["<Esc>"], run = "close", desc = "Cancel input" }]
