"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
ratio = [1, 4, 3]
sort_by = "natural"
sort_reverse = false
sort_dir_first = true
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900

[plugin]
prepend_previewers = [
  { name = "*.md", run = "glow" }
  # { name = "*.md", run = "sh -c \"CLICOLOR_FORCE=1 glow\")" },
]

[[plugin.prepend_fetchers]]
id   = "git"
name = "*"
run  = "git"

