"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"
# default setting https://github.com/sxyazi/yazi/blob/shipped/yazi-config/preset/yazi-default.toml

[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_reverse = false
sort_dir_first = true
show_hidden = true
show_symlink = true

[preview]
tab_size = 2
max_width = 600
max_height = 900

[plugin]
prepend_previewers = [
  { name = "*.md", run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"' }, # force color due to https://github.com/charmbracelet/glow/issues/654
]

[[plugin.prepend_fetchers]]
id = "git"
name = "*"
run = "git"
