# ref: https://k9scli.io/topics/config/
k9s:
  ui:
    skin: catppuccin-macchiato
  logger:
    tail: 10000
    buffer: 10000
    sinceSeconds: -1
    textWrap: false
    disableAutoscroll: false
    showTime: false
